---
title: "Systemic Racism in the United States"
author: "Micah Williams"
date: "6/20/2020"
output: html_document
---

```{r setup}

# hide messages b/c many calls to tidycensus
knitr::opts_chunk$set(echo = TRUE,
                      fig.height = 5,
                      fig.width = 9,
                      message = F)
library(tidycensus)
library(tidyverse)
library(readxl)
library(gt)
library(RColorBrewer)
library(maptools)
library(gganimate)

theme_set(theme_minimal() + 
            theme(plot.background = element_rect(fill = '#fdfdfd',
                                                 color = '#fdfdfd')))
```

```{r get_acs_table}
# create table of variable labels
get_labels <- function(tbl.id){
  
  # load in full list of ACS variable names
  acs_18 <- load_variables(2018, 'acs5', cache = T)
  
  acs_18 %>% 
    filter(str_starts(name, tbl.id)) %>%
    mutate(label = str_remove(label, '([:alpha:]+!{2}){0,2}'))
}

# a function for grabbing a whole table from 2018 ACS by state
get_acs_table <- function(tbl.id, race, year = 2018, geography = 'county', ...){
  
  # get table of labels to join with ACS data
  var_labels <- get_labels(tbl.id)
  
  # get data from ACS
  get_acs(geography = geography,
          table = tbl.id,
          year = year,
          summary_var = paste(tbl.id, '001', sep='_'),
          cache_table = T) %>%
    
  # remove 'total' rows, add labels and percentages
  # filter(variable != paste(tbl.id, '001', sep='_')) %>%
  mutate(percent = estimate / summary_est * 100) %>%
  left_join(var_labels,
            by = c('variable' = 'name')) %>%
  mutate(label = as.ordered(label),
         race = race)
}
```

```{r income_data}

# get income data from 2018 ACS
acs_income_black <- get_acs_table('B19001B', 'Black')
acs_income_white <- get_acs_table('B19001A', 'White')

# combine black and white income into single table
us_income <- acs_income_white %>%
  full_join(acs_income_black, by = colnames(acs_income_white))

# summarize states to produce nationwide numbers
brackets <- us_income %>%
  filter(label != 'Total',
         !is.na(estimate), !is.na(summary_est)) %>%
  droplevels() %>%
  select(-percent) %>%
  group_by(label,race) %>%
  nest() %>%
  mutate(percent = map_dbl(data, ~sum(.$estimate) / sum(.$summary_est) * 100)) %>%
  ungroup()

# extract income bracket labels in correct order
bracket.order <- brackets %>% filter(race == 'White') %>% pull(label)

# apply correct label order to original table
brackets$label <- factor(brackets$label, levels = bracket.order)

# calculate summary percentages for income levels (>$75k, <$50k)
brackets %>% 
  group_by(race) %>%
  mutate(label_num = row_number(),
         money = case_when(label_num %in% c(1:6) ~ 'less than $35K',
                           label_num %in% c(13:16) ~ 'at least $100K',
                           TRUE ~ 'ignore')) %>%
  filter(money != 'ignore') %>%
  ungroup() %>%
  group_by(race, money) %>%
  summarize(sum.pct = sum(percent))
```

```{r income_plot, message = T}

# draw plot, customize with themes and labels
brackets %>% 
  filter(label != 'Total') %>%
  
  ggplot() +
  geom_col(aes(label, percent, fill = race),
           position = position_dodge(0.6), alpha = 0.8) +
  
  # change scales for bar fills and y axis
  scale_fill_brewer(palette = 'Paired', direction = -1) +
  scale_y_continuous(breaks = seq(0,12,4),
                     labels = paste(seq(0,12,4), '%', sep = '')) +
  theme(axis.text.x = element_text()) +
  
  # add labels to axes and title
  labs(title = 'Household Income by Race in the United States',
       subtitle = 'Includes data from all 50 states, plus Washington D.C. and Puerto Rico.',
       caption = 'Source: 2018 American Community Survey',
       fill = 'Race',
       y = 'Percent in Income Bracket',
       x = 'Household Income in Last 12 Months') +
  
  # flip axes to orient bars horizontally
  coord_flip()

# save plot to files
ggsave('images/income.png', height = 5, width = 9, dpi = 'retina')

```

```{r white_wealth_data}
# get acs data for black population
black_pops <- get_acs('county',
                      year = 2018,
                      variables = 'B01001B_001',
                      summary_var = 'B01001_001',
                      cache_table = T) %>%
  select(everything(), total.pop = summary_est, -c(moe, summary_moe)) %>%
  mutate(race = 'Black')

white_pops <- get_acs('county',
                      year = 2018,
                      variables = 'B01001A_001',
                      summary_var = 'B01001_001',
                      cache_table = T) %>%
  select(everything(), total.pop = summary_est, -c(moe, summary_moe)) %>%
  mutate(race = 'White')

pops <- black_pops %>%
  full_join(white_pops, by = c('GEOID', 'NAME', 'race', 'variable', 'estimate', 'total.pop'))

# find FIPS codes for top 100 counties by black pop
black_fips <- black_pops %>% 
  mutate(percent = 100 * estimate / summary_est) %>%
  arrange(desc(percent)) %>%
  # slice(1:100) %>%
  select(black.pop = estimate, percent, GEOID)

# find income data for above counties
income_acs <- get_acs('county',
                         year = 2018,
                         variables = 'B19013B_001',
                         summary_var = 'B19013A_001',
                         cache_table = T) %>%
  mutate(white.factor = summary_est / estimate) %>%
  full_join(black_fips, by = c('GEOID'))

# rename columns for clearer names, filter out counties with very small black populations
county_income <- income_acs %>%
  filter(!is.na(moe), percent >= 5) %>%
  arrange(desc(white.factor)) %>%
  select(GEOID, NAME, black.income = estimate, white.income = summary_est, white.factor:percent) %>%
  mutate(white.income = white.income / 1000,
         black.income = black.income / 1000)

# create linear model of income and percet black
income_model <- lm(white.income ~ black.income, data = county_income)
rsq <- summary(income_model)$r.squared
coefs <- income_model$coefficients

# create tibble for line labels
lines <- tibble(x = c(107,106),
                y= c(96, 133),
                labels = c('\'Ideal\' Line',
                           'Line of Best Fit'),
                bold = c(1,2))

lbf.height = 18.75

rsq_text <- tibble(x = c(106, 75),
                y= c(127, lbf.height),
                labels = c('R^2==0.522',
                           'white.income == 0.841 %*% black.income + 26539.83'),
                hjust = c(0.5,0.2),
                bold = 2)
```

```{r white_wealth_plot, fig.height=5, fig.width=9}
# create plot
county_income %>%
  ggplot() +
  
  # add points for counties
  geom_point(aes(black.income, white.income),
             alpha = 0.4,
             pch = 19,
             color = '#6baed6') +
  
  # add line of best fit and 'ideal' line
  geom_abline(slope = coefs['black.income'], 
              intercept = coefs['(Intercept)'],
              size = 1.5, color = '#377EB8') +
  geom_abline(slope = 1, intercept = 0, lty = 2) + 
  
  # add labels for lines
  geom_text(aes(x = x, y = y, 
                label = labels, 
                fontface = bold),
            data = lines)+
  
  # simplify scales for readability
  scale_x_continuous(breaks = seq(0,125,25),
                     labels = paste('$', seq(0,125,25), 'K', sep = '')) +
  scale_y_continuous(breaks = seq(0,125,25),
                     labels = paste('$', seq(0,125,25), 'K', sep = '')) +
  
  # add labels, title, etc.
  labs(title = 'Median Household Income, Black vs. White by County',
       subtitle = 'Includes counties in the 50 states, D.C., and Puerto Rico where the black population is at least 5% of the white population.',
       x = 'Median Household Income, Black',
       y = 'Median Household Income, White',
       caption = 'Source: 2018 American Community Survey') +
  
  # add legend for best fit (separate because parse = T)
  geom_text(aes(x = x, y = y, 
                label = labels,
                hjust = hjust),
            parse = T,
            fontface = 2,
            data = rsq_text) +
  
  geom_segment(aes(x = 61, xend = 64,
                   y = lbf.height, yend = lbf.height),
               size = 1.5, color = '#377EB8')

 ggsave('images/county_income.png', width = 9, height = 5, dpi = 'retina')
```

```{r education_data}
# get education data from 2018 ACS at national level
edu_white <- get_acs_table('C15002A', 'White', geography = 'county')
edu_black <- get_acs_table('C15002B', 'Black', geography = 'county')

# get populations by race and sex
race_sex_pops <- get_acs('county',
                         year = 2018,
                         variables = c('B01001A_002',
                                       'B01001A_017',
                                       'B01001B_002',
                                       'B01001B_017'),
                         cache_table = T) %>%
  select(-moe)

# join black and white tables together
edu_county <- full_join(edu_white, edu_black, by = colnames(edu_white)) %>%
  
  # add column for sex and further clean labels to show only education level
  mutate(sex = case_when(str_starts(label, 'Male') ~ 'Male',
                         TRUE ~ 'Female'),
         label = str_remove(label, '[:alpha:]+!{2}')) %>%
  
  # remove incorrect summary_est column and summary rows for each sex and total
  select(-summary_est) %>%
  filter(!label %in% c('Male', 'Female', 'Total')) %>%
  
  # calculate new summary column by state, sex, and race
  group_by(GEOID, sex, race) %>%
  nest() %>%
  mutate(summary_est = map_dbl(data, ~ sum(.$estimate))) %>%
  unnest(data) %>%
  ungroup() %>%
  
  # add columns for group (ex. 'White Males'), convert education levels to factor
  mutate(demo = paste(race, ' ', sex, 's', sep = ''),
         percent = estimate / summary_est * 100)

# extract factor order for labelling
fct_order <- edu_county %>% 
  filter(variable %in% paste('C15002A_00', c(3:6), sep = '')) %>%
  slice(1:4) %>%
  pull(label) %>%
  rev()

# relevel labels to match sequence of educational attainment
edu_county$label <- factor(edu_county$label, levels = fct_order)

edu_us <- edu_county %>%
  
  # drop county percentages
  select(-percent) %>%
  
  # calculate percentages by education level, race, and sex
  group_by(label, race, sex, variable) %>% 
  nest() %>%
  mutate(percent = map_dbl(data, ~ sum(.$estimate) / sum(.$summary_est) * 100)) %>%
  select(-data)

# combine education and population data to make education by race table
edu_race <- edu_county %>%
  group_by(race, GEOID, label) %>%
  summarize(est.both = sum(estimate),
            est.all = sum(summary_est),
            percent = est.both / est.all * 100) %>%
  select(-c(est.both, est.all))

edu_income <- county_income %>%
  select(-white.factor) %>%
  pivot_longer(cols = c(black.income, white.income),
               values_to = 'income',
               names_to = 'race',
               names_pattern = '([:alpha:]{5})') %>%
  mutate(race = str_to_title(race),
         inc_rank = percent_rank(income) * 100) %>%
  select(GEOID, race, income, inc_rank) %>%
  full_join(edu_race, by = c('GEOID', 'race')) %>%
  
  filter(!is.na(percent), !is.na(inc_rank))

edu_inc_model <- edu_income %>% 
  filter(label == levels(label)[1]) %>%
  lm(percent ~ income, data = .)

broom::tidy(edu_inc_model)

lbf.height = 90

rsq_text <- tibble(x = c(43.5, 45),
                y= c(85,lbf.height),
                labels = c('R^2==0.535',
                           'percent == 0.463 %*% income.thousands - 1.43'),
                bold = 2)

edu_income %>%
  filter(race == 'Black') %>%
  group_by(label) %>%
  nest() %>%
  mutate(mod = map(data, ~lm(percent ~ inc_rank, data = .)),
         rsq = map_dbl(mod, ~summary(.)$r.squared),
         coefs = map(mod, ~.$coefficients)) %>%
  ungroup()

edu_income %>%
  filter(race == 'Black') %>%
  group_by(label) %>%
  nest() %>%
  mutate(mod = map(data, ~lm(percent ~ income, data = .)),
         rsq = map_dbl(mod, ~summary(.)$r.squared),
         coefs = map(mod, ~.$coefficients)) %>%
  ungroup()

one_sum <- function(v){
  append(v[1], sum(v))
}

# rm(edu_white, edu_black)
```

```{r education_plot}
# education column by race and sex
edu_us %>%
  
  # add position column for demographic labels
  group_by(race, sex) %>%
  mutate(position = cumsum(percent) - percent / 2,
         demo = paste(race, sex, sep = ' ')) %>%
  ungroup() %>%

  # draw stacked bar plot by group with text labels
  ggplot(aes(demo, percent, label, fill = label)) +
  geom_col() +
  geom_text(aes(label = round(percent, 1), y = position)) +
  
  # customize plot with new palette, cleaned labels for axes, title, caption
  scale_fill_brewer(palette = 'Blues', direction = -1) +
  scale_y_continuous(breaks = seq(0,100,25), labels = paste(seq(0,100,25), '%', sep = '')) +
  labs(x = '', y = 'Percentage',
       title = 'Educational Attainment by Race and Sex, Americans 25 and Older',
       
       # subtitle for plot with both
       subtitle = 'Black men and women are both less likely than their white counterparts to attain post-secondary education.',
       
       caption = 'Source: 2018 American Community Survey.\nPercentages are rounded.',
       fill = 'Highest Educational Attainment') +
  
  # remove unnecessary lines on axes
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank()) +
  
  # flip axes for horizontal plot instead of vertical bars
  coord_flip()

# save plot to files
ggsave('images/education_race.png', height = 5, width = 9, dpi = 'retina')
```

```{r income_education_plots}
BuPu <- brewer.pal(5, 'BuPu')[2:5]

# filter out white data
edu_income %>% # filter(race == 'Black') %>% 
  
  # create scatterplot
  ggplot() +
  geom_boxplot(aes(race, inc_rank, fill = race),
               outlier.shape = NA,
             alpha = 0.5) +
  
  # edit scales to include percent signs, change colors
  scale_y_continuous(breaks = seq(0,100,20),
                     labels = paste(seq(0,100,20), '%', sep = '')) +
  scale_fill_brewer(palette = 'Paired', direction =  -1) +
  
  # add labels for title, subtitle, axes, source, legend 
  labs(title = 'Distribution of Median Household Income, by Race',
       subtitle = 'Black populations are concentrated at lower income levels compared to white populations: 3 in 4 black populations\nare in the bottom 42% of income rankings including black and white populations in counties across the US.',
       x = 'Race',
       y = 'Median Household Income Percentile Rank',
       color = 'Highest\nEducational\nAttainment',
       caption = 'Source: 2018 American Community Survey') +
  
  # change legend position and layout
  theme(legend.position = 'bottom',) +
  guides(fill = 'none') +
  
  coord_flip()

# save plot to files
ggsave('images/inc_edu_black.png', width = 9, height = 5, dpi = 'retina')
  
# create table showing distribution of black household income
cut(edu_income[edu_income$race == 'Black', ]$inc_rank, breaks = c(0, 42, 100)) %>% 
  table() %>% prop.table()

edu_income %>% filter(race == 'Black') %>% 
  
  # create scatterplot, split by education level
  ggplot() +
  geom_point(aes(inc_rank, percent, color = label),
             alpha = 0.5,
             pch = 16) +
  
  # add vertical lines
  geom_vline(xintercept = 42, color = '#777777', lty = 2, size = 0.6) +

  # edit scales to include percent signs
  scale_x_continuous(breaks = seq(0,100,20),
                     labels = paste(seq(0,100,20), '%', sep = '')) +
  scale_y_continuous(limits = c(0,80),
                     breaks = seq(0,80,20),
                     labels = paste(seq(0,80,20), '%', sep = '')) +
  scale_color_manual(values = BuPu) +
  
  # break graphs apart by education level
  facet_wrap(~label) +
  
  # add labels for title, subtitle, axes, source, legend 
  labs(title = 'Median Household Income vs. Educational Attainment, by County (Black Only)',
       subtitle = 'As income increases, educational attainment increases. However, black populations are concentrated at the lower levels\nof the income scale. Three quarters of counties are to the left of the dotted line.',
       y = 'Percent of County',
       x = 'Median Household Income Percentile Ranking',
       color = 'Highest\nEducational\nAttainment',
       caption = 'Source: 2018 American Community Survey') +
  
  # change legend position and layout
  theme(legend.position = 'none',)

# save plot to files
ggsave('images/inc_edu_split.png', width = 9, height = 5, dpi = 'retina')

paired.cols <- brewer.pal(4, 'Paired')[c(1,4,2,3)]

edu_income %>% 
  filter(label %in% levels(edu_income$label)[c(1,2)]) %>%
  
  # join education percentages with populations for weighting
  left_join(pops, by = c('GEOID', 'race')) %>%
  
  mutate(inc_grp = cut(inc_rank, breaks = seq(0,100,10),
                       include.lowest = T)) %>%
  
  group_by(inc_grp, race, label) %>%
  summarize(avg.pct = weighted.mean(x = percent,
                                    w = estimate,
                                    na.rm = T)) %>%
  ungroup() %>%
  mutate(col.group = rep(c('bh','bl','wh','wl'), 10)) %>%
  
  # fake stacked barplot by adding bars together for one of the levels
  group_by(inc_grp, race) %>%
  nest() %>%
  mutate(avg.pct = map_dbl(data, ~append(.$avg.pct[1], sum(.$avg.pct))))
    
  # create barplot, split by education level
  ggplot() +
  geom_col(aes(inc_grp, avg.pct,
               group = race,
               fill = col.group),
             alpha = 1,
           position = position_dodge()) +

  # edit scales to include percent signs
  # scale_y_continuous(limits = c(0,80),
  #                    breaks = seq(0,40,10),
  #                    labels = paste(seq(0,40,10), '%', sep = '')) +
  scale_fill_manual(values = paired.cols[c(3,1,2,4)], 
                    breaks = c('bh','bl','wh','wl')) +
  
  # facet_wrap(~label) +
  
  # add labels for title, subtitle, axes, source, legend 
  labs(title = 'Average Percent with Bachelor\'s degree or higher, by Median Household Income Ranking',
       subtitle = 'White populations in the lowest 30% of income rankings, while somewhat unlikely to have a Bachelor\'s degree or higher, are still more likely than black populations\nat the same income levels. As income increases, attainment of advanced degrees increases faster for white populations\nthan for black populations.',
       y = 'Percent with Bachelor\'s degree or higher',
       x = 'Median Household Income Percentile Ranking',
       color = 'Race',
       caption = 'Source: 2018 American Community Survey') +
  
  # change legend position and layout
  theme(legend.position = 'bottom') +
  coord_flip()
```


```{r income_education_plots}
# save plot to files
ggsave('images/inc_edu_bachelors_WT.png', width = 9, height = 5, dpi = 'retina')

edu_income %>%
  filter(label == levels(label)[1]) %>%
  ggplot(aes(income, percent)) +
  geom_point(color = 'maroon',
             alpha = 0.3) +
  
  geom_abline(slope = edu_inc_model$coefficients[2],
              intercept = edu_inc_model$coefficients[1],
              color = '#884088',
              size = 1.5) +
  
  # edit scales to include percent signs
  scale_x_continuous(breaks = seq(0,140,20),
                     labels = paste('$', seq(0,140,20), 'K', sep = '')) +
  scale_y_continuous(limits = c(0,100),
                     breaks = seq(0,100,25),
                     labels = paste(seq(0,100,25), '%', sep = '')) +
  
  # add labels for title, subtitle, axes, source, legend 
  labs(title = 'Median Household Income vs. Attainment of Bachelor\'s Degree or higher, by County',
       subtitle = 'As median household income increases, attainment of advanced degrees increases. Median household income in\nmost counties is concentrated between around $20K/year and $60K/year.',
       y = 'Percent with Bachelor\'s degree or higher',
       x = 'Median Household Income',
       caption = 'Source: 2018 American Community Survey') +
  
  # add legend for best fit (separate because parse = T)
  geom_text(aes(x = x, y = y, 
                label = labels,
                fontface = 2),
            parse = T,
            data = rsq_text) +
  
  geom_segment(aes(x = 17, xend = 20,
                   y = lbf.height, yend = lbf.height),
               size = 1.5, color = '#884088')

ggsave('images/inc_edu_norace.png', width = 9, height = 5, dpi = 'retina')

edu_income %>%
  filter(label == levels(label)[1]) %>%
  ggplot(aes(inc_rank, percent)) +
  geom_point(alpha = 0.3,
             color = 'maroon') +
  
  # edit scales to include percent signs
  scale_x_continuous(breaks = seq(0,100,20),
                     labels = paste(seq(0,100,20), '%', sep = '')) +
  scale_y_continuous(limits = c(0,100),
                     breaks = seq(0,100,25),
                     labels = paste(seq(0,100,25), '%', sep = '')) +
  
  # add labels for title, subtitle, axes, source, legend 
  labs(title = 'Median Household Income Rank vs. Educational Attainment, by County',
       subtitle = 'As median household income increases, attainment of advanced degrees increases.',
       y = 'Percent with Bachelor\'s degree or higher',
       x = 'Median Household Income Percentile Ranking',
       caption = 'Source: 2018 American Community Survey')

ggsave('images/inc_rank_norace.png', width = 9, height = 5, dpi = 'retina')
```

```{r income_rank_animation, fig.width=9, fig.height=5}
anim.data <- county_income %>%
  select(default = black.income,
         y = white.income) %>%
  mutate(Ranked = percent_rank(default),
         Original = (default - min(default)) / (max(default) - min(default)))

rank_anim <- anim.data %>%
  pivot_longer(cols = c(Original, Ranked),
               names_to = 'anim.state',
               values_to = 'x') %>%
  select(x, y, anim.state) %>%
  ggplot(aes(x, y)) +
  geom_point(color = 'maroon', alpha = 0.3) +
  
  #remove axis labels
  labs(x = '', y = '',
       title = 'Animation Showing x-axis Transition from Original Data to Percentile Ranking',
       subtitle = paste('x-axis: ', '{closest_state}', ' data', sep = '')) +
  theme(axis.text = element_blank()) +
  
  # add animation
  transition_states(anim.state)

animate(rank_anim, width = 9, height = 5, units = 'in', res = 300)

anim_save('images/ranking_anim.gif', width = 9, height = 5, units = 'in', dpi = 'retina')
```

```{r county_coords}
# import geometry from shapefiles
county_geom <- rgdal::readOGR(dsn = './data/gz_2010_us_050_00_5m','gz_2010_us_050_00_5m')

# below code heavily sampled from https://www.r-bloggers.com/moving-the-earth-well-alaska-hawaii-with-r/
# rearrange Alaska and Hawaii to be near lower 48 states

# select Hawaii geom from county file
hawaii <- county_geom[county_geom$STATE == '15',] %>%
  
  # scale up to double size, move to below southwest USA
  elide(scale=max(apply(bbox(.), 1, diff)) * 2) %>% 
  elide(shift=c(-113, 23))

# assign proj4string so that new Hawaii geom can replace old geom
hawaii@proj4string <- county_geom@proj4string

# select Alaska geom from county file
alaska <- county_geom[county_geom$STATE == '02',] %>%
  
  # scale to one-third(ish) size, rotate slightly, move to near new Hawaii location
  elide(scale = max(apply(bbox(.), 1, diff)) / 3.4) %>%
  elide(rotate = -5) %>%
  elide(shift = c(-123, 20.5))

# assign proj4string so that new Alaska can replace old geom
alaska@proj4string <- county_geom@proj4string

# replace old Alaska and Hawaii geoms with edited versions
county_geom <- rbind(county_geom[!county_geom$STATE %in% c('15','02'),],
                    hawaii, alaska)

# convert geometry file to tidy dataframe for plotting
county_coords <- fortify(county_geom, region = 'GEO_ID') %>%
  
  # extract state and county FIPS codes
  mutate(state_code = str_extract(id, '(?![:alnum:]{9})[:digit:]{2}'),
         GEOID = str_extract(id, '(?![:alnum:]{9})[:digit:]{5}')) %>%

  #filter out extreme Alaskan islands that were mangled in the move
  filter(long < -60)
  
# combine county polygons by state to create state polygons
state_geom <- unionSpatialPolygons(county_geom, county_geom$STATE)

# convert state geometry to tidy dataframe for plotting
state_coords <- fortify(state_geom) %>%
  
  # rename state code column, filter out Puerto Rico and mangled Alaskan islands
  select(state = id, everything()) %>%
  filter(state != '72', long < -60)
```

```{r education_map}
# get educational attainment data from 2018 ACS
edu_black_hs <- edu_county %>%
  
  # filter for black males with less than hs diploma
  filter(race == 'Black',
         sex == 'Male',
         variable != 'C15002B_003') %>%
  group_by(GEOID) %>%
  summarize(percent = sum(percent))
  
edu_black_hs %>%
  
  # join ACS data with county coordinates for map plot
  full_join(county_coords, by = 'GEOID') %>%
  
  # filter out Puerto Rico
  filter(!str_starts(GEOID, '72')) %>%

  # plot map, filled by black male educational attainment (more than HS)
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = percent),
               color = '#666666',
               size = 0.2) +
  
  # change map projection
  coord_map('conic', lat0 = 30) +
  
  # change color scales to match percentage distribution
  scale_fill_gradientn(breaks = rev(c(0, 85, 92, 96, 100)),
                       values = rev(c(0, 85, 92, 96, 100)) / 100,
                       colors = rev(brewer.pal(4, 'RdYlGn')),
                       na.value = 'gray',
                       guide = 'legend',
                       labels = rev(c('0-85%', '85-92%', '92-96%', '96-100%', '100%'))) +

  # add state boundary lines
  geom_path(aes(long, lat, group = group, fill = NULL),
            color = '#666666',
            data = state_coords) +
  
  # add title and source note
  labs(title = 'Percent of Black Males With At Least High School Diploma, by County',
       subtitle = 'Nationwide, highest educational attainment for 16.1% of black men is less than a high school diploma.',
       caption = 'Source: 2018 American Community Survey. Data for some counties missing.') +
  
  # remove theme, relocate legend
  theme_void() +
  theme(legend.position = c(0.9, 0.5),
        legend.title = element_blank())

# save map to files
ggsave('images/education_map.png', width = 9, height = 5, dpi = 'retina')
```
  
```{r homes_data, warning = F, message = F}
# suppress warnings and messages about columns and rows that are later discarded

# skip empty rows at top of table, set column types, clean column names with janitor
homes <- read_excel('data/ann19t_22.xlsx', skip = 3, col_types = c('text', rep('numeric',27))) %>%
  janitor::clean_names() %>%
  
  # rename 1996 column to remove 'footnote'1' superscript, remove 2002 column to use revised data
  select(race = x1, x1996 = x19961, everything(), 
         -x2002, x2002 = x2002r1) %>%
  
  # extract relevant rows
  slice(4:6) %>%
  
  # pivot table to tidy format
  pivot_longer(., cols = x1996:x2019, 
               names_to = 'year', values_to = 'percent',
               names_prefix = 'x') %>%
  
  # clean labels for race
  mutate(race = str_extract(race, '([:alpha:]{5}|[:alpha:]{3}\\-[:alpha:]{8}[:blank:][:alpha:]{5})'),
         year = as.numeric(year))

# create table for annotations
rl <- tibble(x = c(2006.5), y = c(77.5,50),
             race = c('Non-Hispanic White', 'Black'))

# create table of points to highlight
home.pnts <- homes %>%
  filter(year %in% c(range(year), 2004), race != 'White') %>%
  mutate(label.y = case_when(race == 'Black' ~ percent - 4,
                             TRUE ~ percent + 4))
```

```{r homes_plot}

# plot line graph time series of Blacks and Non-Hispanic Whites
homes %>%
  filter(race != 'White') %>%
  
  ggplot() +
  geom_line(aes(year, percent, color = race),
            size = 1.5) +
  
  # add highlight points and labels on ends
  geom_point(aes(year, percent, color = race),
             size = 4, pch = 21, stroke = 2.5,
             fill = 'white',
             data = home.pnts) +
  geom_text(aes(year, label.y, label = percent, color = race),
            size = 4.5,
            data = home.pnts) +
  
  # add line labels
  geom_text(aes(x, y, label = race, color = race), 
            fontface = 2, hjust = 0,
            data = rl) +
  
  # change color, axes scales
  scale_color_manual(values = c('#377EB8', '#6baed6')) +
  scale_y_continuous(limits = c(30, 90),
                     breaks = seq(20,90,10),
                     labels = paste(seq(20,90,10), '%', sep = '')) +
  scale_x_continuous(limits = c(1994,2020),
                     breaks = seq(1995,2020,5),
                     labels = c('\'95', '2000', paste('\'', c('05', 10, 15, 20), sep = ''))) +
  
  # add title and axes labels
  labs(y = 'Percentage of Home Ownership',
       x = 'Year',
       title = 'Percentage of Home Ownership by Race, 1994-2019',
       subtitle = 'The disparity in home ownership between Blacks and Non-Hispanic Whites, about 31% in 2019, has remained relatively\nconstant over the last 25 years.',
       caption = 'Source: U.S. Census Bureau, Current Population Survey/Housing Vacancy Survey, March 10, 2020.') +
  
  # remove minor grid lines and legend
  theme(panel.grid.minor = element_blank(),
        legend.position = 'none')

ggsave('images/homes.png', width = 9, height = 5, dpi = 'retina')

diff.area %>% 
  mutate(diff = NHW - Black) %>% 
  summarize(mean = mean(diff), min = min(diff), max = max(diff))
```

```{r prison_data, message = F, warning = F}
# load in 2018 data, skipping non-data rows and removing empty columns
# note: data is X per 100,000 people
prison.18 <- read_csv('data/prison/p18/p18t06.csv', skip = 11) %>%
  select(-starts_with('X')) %>%
  janitor::clean_names() %>%
  slice(1:11) %>%
  
  # change year to numeric, remove old year column
  mutate(year = as.numeric(year_a)) %>%
  select(year, everything(), -year_a)


# remove extra bits from column names
colnames(prison.18) <- str_remove(colnames(prison.18), '_[:alpha:]')

prison.race <- prison.18 %>%
  
  # select relevant columns
  select(year, white, black, total) %>%
  
  # convert table to tidy format (race column, rate column)
  pivot_longer(cols = c(white, black, total), names_to = 'race', values_to = 'rate')

prison.ribbon <- prison.18 %>% select(year, black, white)
prison.labels <- tibble(x = c(2013.5),
                        y = c(1930,170,750),
                        labels = c('black', 'white', 'national rate'))

race.dots <- prison.race %>% group_by(race) %>% filter(year %in% c(min(year), max(year)))
race.labels <- race.dots %>% mutate(label.y = case_when(
  year == 2018 & race == 'black' | race == 'total' ~ rate + 170,
  TRUE ~ rate - 170))

# create year labels for plot
year_labels <- paste('\'', str_remove(seq(1980,2020,5), '[:digit:]{2}'), sep = '')
year_labels[5] <- '2000'

# load in data from appendix table (national rate per 100,000 adults)
bjs_total <- read_csv('data/prison/p18/p18at01.csv', skip = 10) %>%
  mutate(year = as.numeric(Year)) %>%
  select(year, rate = 'Age 18 or older') %>%
  slice(-42)

# create tibble of dots to highlight and labels
bjs.dots <- bjs_total %>% filter(year %in% c(1978, 2008, 2018))
bjs.labels <- bjs.dots %>% mutate(label.y = case_when(year == 1978 ~ rate + 35,
                                              TRUE ~ rate - 35))

# create table showing rate of Black Incarceration as multiple of White rate
prison.ribbon %>% mutate(rate.multiple = black / white) %>% slice(1,11)

# create tables of percent changes in incarceration rates from 2008-2018
race.labels %>% group_by(race) %>% summarize(pct.change = (rate[2] - rate[1]) / rate[1])
```

```{r prison_plot, message = F, warning = F}
# draw plot of incarceration rates by race
prison.race %>%
  
  # add line plots
  ggplot() +
  geom_line(aes(year, rate, color = race),
            size = 1.5) +
  
  # add highlight points
  geom_point(aes(year, rate, color = race),
             size = 4, pch = 21, stroke = 2.5,
             fill = 'white',
             data = race.dots) +
  geom_text(aes(year, label.y, label = rate, color = race),
            size = 4.75,
            data = race.labels) +
  
  # add labels to lines
  geom_text(aes(x, y, label = str_to_title(labels), color = labels),
            fontface = 2,
            data = prison.labels) +
  
  # add title, subtitle, axes labels, caption
  labs(title = 'U.S. Incarceration Rates by Race, 2008-2018',
       subtitle = 'While the difference in incarceration rates has narrowed in recent years, in 2018 black Americans were\nincarcerated at 2.7 times the national average, and 5.6 times the rate of white Americans.', 
       x = 'Year', y = 'Incarceration Rate\n(per 100,000 adults)',
       caption = 'Source: Bureau of Justice Statistics, Federal Justice Statistics Program, U.S. Census Bureau') +
  
  # modify scales to fit data and match color schemes
  scale_x_continuous(limits = c(2008,2018),
                     breaks = c(2008:2018),
                     labels = c('\'08', '\'09', 2010, paste('\'', c(11:18), sep = ''))) +
  scale_y_continuous(limits = c(0,2250)) +
  scale_color_manual(values = c('#377EB8', '#003333', '#003333', '#6baed6')) +
  
  theme(panel.grid.minor.x = element_blank(),
        legend.position = 'none')

ggsave('images/prison.png', width = 9, height = 5, dpi = 'retina')

# create plot of total imprisonment rate in US, '78-'16
ggplot(aes(year, rate), data = bjs_total) +
  geom_line(size = 1.5, color = 'maroon') +
  
  # add points to highlight and labels
  geom_point(size = 4, pch = 21, stroke = 2.5,
             color = 'maroon', fill = 'white',
             data = bjs.dots) +
  geom_text(aes(year, label.y, label = rate),
            size = 4.75, color = 'maroon',
            data = bjs.labels) +
  
  # add title and change axes
  labs(title = 'United States Incarceration Rate, 1978-2018',
       subtitle = 'The incarceration rate in the US nearly quadrupled from 1978 to 2007, but has been in decline since the late 2000\'s.',
       x = 'Year', y = 'Incarceration Rate\n(per 100,000 adults)',
       caption = 'Source: Bureau of Justice Statistics, National Prisoner Statistics') +
  
  # change labels on x axis
  scale_x_continuous(breaks = seq(1980,2020,5),
                     labels = year_labels) +
  
  # remove minor grid lines
  theme(panel.grid.minor.x = element_blank())

ggsave('images/prison_totals.png', width = 9, height = 5, dpi = 'retina')
```

```{r county_income_gt}
# create gt of top ten counties with highest white/black income
county_income %>% 
  
  # arrange by white income multiplier, add ranking
  arrange(desc(white.factor)) %>% 
  mutate(white.income = white.income * 1000,
         black.income = black.income * 1000,
         Rank = row_number()) %>%
  
  # select top 10 rows and rearrange/drop columns for table order
  slice(1:10) %>% 
  select(Rank, everything(), -c(GEOID, percent)) %>% 
  
  # create gt and add title, income spanner group
  gt() %>%
  tab_header(title = 'Median Household Income by Race and County',
             subtitle = 'Ten Counties with highest \'White Income Multiplier\' are shown') %>%
  tab_spanner(columns = vars(black.income,white.income),
              label = 'Median Household Income') %>%
  
  # align columns and reformat numbers, incomes
  cols_align('center', columns = vars(black.income, white.income, black.pop, white.factor)) %>%
  fmt_currency(columns = vars(black.income, white.income),
               decimals = 0) %>%
  fmt_number(columns = vars(black.pop), decimals = 0) %>%
  fmt_number(columns = vars(white.factor), decimals = 3) %>%
  
  # rename columns
  cols_label(NAME = 'County',
             black.income = 'Black',
             white.income = 'White',
             black.pop = 'Black Population',
             white.factor = 'White Income Multiplier')
  
```


