---
title: "Systemic Racism in the United States"
author: "Micah Williams"
date: "6/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.height = 5,
                      fig.width = 9)
library(tidycensus)
library(tidyverse)
library(readxl)
library(gt)
library(RColorBrewer)
library(maptools)

theme_set(theme_minimal())
ribbon.fill = rgb(1,0.3,0.2,0.1)
```

```{r get_acs_table}
# create table of variable labels
get_labels <- function(tbl.id){
  
  # load in full list of ACS variable names
  acs_18 <- load_variables(2018, 'acs5', cache = T)
  
  acs_18 %>% 
    filter(str_starts(name, tbl.id)) %>%
    mutate(label = str_remove(label, '([:alpha:]+!{2}){0,2}'))
}

# a function for grabbing a whole table from 2018 ACS by state
get_acs_table <- function(tbl.id, race, year = 2018, ...){
  
  # get table of labels to join with ACS data
  var_labels <- get_labels(tbl.id)
  
  # get data from ACS
  get_acs(geography = 'state',
                        table = tbl.id,
                        year = year,
                        summary_var = paste(tbl.id, '001', sep='_'),
                        cache_table = T) %>%
  
  # remove 'total' rows, add labels and percentages
  # filter(variable != paste(tbl.id, '001', sep='_')) %>%
  mutate(percent = estimate / summary_est * 100) %>%
  left_join(var_labels,
            by = c('variable' = 'name')) %>%
  mutate(label = as.ordered(label),
         race = race)
}
```

```{r income_data}
# message = F to supress messages from get_acs()

acs_income_black <- get_acs_table('B19001B', 'Black')
acs_income_white <- get_acs_table('B19001A', 'White')

# combine black and white income into single table
us_income <- acs_income_white %>%
  full_join(acs_income_black, by = colnames(acs_income_white))

cali_income <- us_income %>% 
  filter(GEOID == '06')

# calculate summary percentages for income levels ( >$75k, <$50k)
us_income %>% 
  mutate(var_ext = as.numeric(str_remove(variable, '[:alnum:]{7}_')),
         inc_level = case_when(var_ext >= 12 ~ '>$75k/yr',
                               var_ext <= 7 ~ '<$35k/yr',
                               TRUE ~ 'ignore')) %>%
  filter(inc_level != 'ignore') %>%
  group_by(inc_level, race) %>%
  nest() %>%
  mutate(total_indiv = map_dbl(data, ~ sum(.$estimate)),
         total_pop = map_dbl(data, ~ sum(unique(.$summary_est))),
         percent = total_indiv / total_pop * 100) %>%
  select(race, inc_level, percent) %>%
  .[c(1,3,2,4),]
```

```{r income_plot, message = T}

# summarize states to produce nationwide numbers
brackets <- us_income %>%
  droplevels() %>%
  group_by(label,race) %>%
  summarize(percent = sum(estimate) / sum(summary_est) * 100) %>%
  ungroup()

# create table of income levels and extract leading values (ex. extract '100' from '$100,000')
bracket.order <- brackets %>%
  select(label) %>%
  
  # take one row per bracket
  group_by(label) %>%
  slice(1) %>%
  ungroup() %>%
  
  # extract min. value of bracket
  mutate(label.ext = str_remove(str_extract(levels(brackets$label),
                                 '([:alpha:]*[:blank:])*\\$[:digit:]{2,3}'),
                                '\\$'))
# replace 'Less than 10' level with 1 for ordering
bracket.order[16,2] <- 1

# arrange table rows in correct order
bracket.order <- bracket.order %>%
  mutate(label.ext = as.numeric(label.ext)) %>%
  arrange(label.ext)

# apply correct label order to original table
brackets$label <- factor(brackets$label, levels = bracket.order$label)

# draw plot, customize with themes and labels
brackets %>% 
  filter(label != 'Total') %>%
  
  # remove data for black people
  # mutate(percent = case_when(race == 'Black' ~ NA_real_,
  #                            TRUE ~ percent)) %>%
  
  ggplot() +
  geom_col(aes(label, percent, fill = race),
           position = position_dodge(0.6), alpha = 0.8) +
  
  # change scales for bar fills and y axis
  scale_fill_brewer(palette = 'Paired', direction = -1) +
  scale_y_continuous(breaks = seq(0,12,4),
                     labels = paste(seq(0,12,4), '%', sep = '')) +
  theme(axis.text.x = element_text()) +
  
  # add labels to axes and title
  labs(title = 'Household Income by Race in the United States',
       subtitle = 'Includes data from all 50 states, plus Washington D.C. and Puerto Rico.',
       caption = 'Source: 2018 American Community Survey',
       fill = 'Race',
       y = 'Percent of Race Group in Income Bracket',
       x = 'Household Income in Last 12 Months') +
  
  # flip axes to orient bars horizontally
  coord_flip()

# save plot to files
# ggsave('images/income.png', height = 5, width = 9, dpi = 'retina')

```

```{r education_data}
# get education data from 2018 ACS
education_white <- get_acs_table('C15002A', 'White')
education_black <- get_acs_table('C15002B', 'Black')

# join black and white tables together
education <- full_join(education_white, education_black, by = colnames(education_white))

# remove obsolete tables
rm(education_black, education_white)

education <- education %>%
  
  # add column for sex and further clean labels to show only education level
  mutate(sex = case_when(str_starts(label, 'Male') ~ 'Male',
                         TRUE ~ 'Female'),
         label = str_remove(label, '[:alpha:]+!{2}')) %>%
  
  # remove incorrect summary_est column and summary rows for each sex and total
  select(-summary_est) %>%
  filter(!label %in% c('Male', 'Female', 'Total')) %>%
  
  # calculate new summary column by state, sex, and race
  group_by(GEOID, sex, race) %>%
  nest() %>%
  mutate(summary_est = map_dbl(data, ~ sum(.$estimate))) %>%
  unnest(data)

us_education <- education %>%
  
  # calculate percentages by education level, race, and sex
  group_by(label, race, sex) %>% 
  nest() %>%
  mutate(percent = map_dbl(data, ~ sum(.$estimate) / sum(.$summary_est) * 100)) %>%
  ungroup() %>%
  
  # add columns for group (ex. 'White Males'), convert education levels to factor
  mutate(group = paste(race, ' ', sex, 's', sep = ''),
         label = as.factor(label))

# relevel labels to match sequence of educational attainment
levels(us_education$label) <- levels(us_education$label)[c(1,4,2,3)]
```

```{r education_plot}
us_education %>%
  
  # add position column for text labels
  group_by(group) %>%
  arrange(group, desc(label)) %>%
  mutate(position = cumsum(percent) - percent / 2) %>%
  ungroup() %>%
  
  # remove data for black people for Whites Only plot
  # mutate(percent = case_when(race == 'Black' ~ NA_real_,
  #                            TRUE ~ percent)) %>%

  # draw stacked bar plot by group with text labels
  ggplot(aes(group, percent, label, fill = label)) +
  geom_col() +
  geom_text(aes(label = round(percent, 1), y = position)) +
  
  # customize plot with new palette, cleaned labels for axes, title, caption
  scale_fill_brewer(palette = 'Blues', direction = -1) +
  scale_y_continuous(labels = paste(seq(0,100,25), '%', sep = '')) +
  labs(x = '', y = 'Percentage',
       title = 'Educational Attainment by Race and Sex, Americans 25 and Older',
       
       # subtitle for white only plot
       subtitle = 'About 60% of White men and women continue their education beyond secondary school.',
       
       # subtitle for plot with both
       subtitle = 'Black men and women are both less likely than their white counterparts to attain post-secondary education.',
       
       caption = 'Source: 2018 American Community Survey.\nPercentages are rounded.',
       fill = 'Highest Educational Attainment') +
  
  # remove unnecessary lines on axes
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank()) +
  
  # flip axes for horizontal plot instead of vertical bars
  coord_flip()

# save plot to files
# ggsave('images/education.png', height = 5, width = 9, dpi = 'retina')
```

```{r county_coords}
# import geometry from shapefiles
county_geom <- rgdal::readOGR(dsn = './data/gz_2010_us_050_00_5m','gz_2010_us_050_00_5m')

# below code heavily sampled from https://www.r-bloggers.com/moving-the-earth-well-alaska-hawaii-with-r/
# rearrange Alaska and Hawaii to be near lower 48 states

# select Hawaii geom from county file
hawaii <- county_geom[county_geom$STATE == '15',] %>%
  
  # scale up to double size, move to below southwest USA
  elide(scale=max(apply(bbox(.), 1, diff)) * 2) %>% 
  elide(shift=c(-113, 23))

# assign proj4string so that new Hawaii geom can replace old geom
hawaii@proj4string <- county_geom@proj4string

# select Alaska geom from county file
alaska <- county_geom[county_geom$STATE == '02',] %>%
  
  # scale to one-third(ish) size, rotate slightly, move to near new Hawaii location
  elide(scale = max(apply(bbox(.), 1, diff)) / 3.4) %>%
  elide(rotate = -5) %>%
  elide(shift = c(-123, 20.5))

# assign proj4string so that new Alaska can replace old geom
alaska@proj4string <- county_geom@proj4string

# replace old Alaska and Hawaii geoms with edited versions
county_geom <- rbind(county_geom[!county_geom$STATE %in% c('15','02'),],
                    hawaii, alaska)

# convert geometry file to tidy dataframe for plotting
county_coords <- fortify(county_geom, region = 'GEO_ID') %>%
  
  # extract state and county FIPS codes
  mutate(state_code = str_extract(id, '(?![:alnum:]{9})[:digit:]{2}'),
         GEOID = str_extract(id, '(?![:alnum:]{9})[:digit:]{5}')) %>%

  #filter out extreme Alaskan islands that were mangled in the move
  filter(long < -60)
  
# combine county polygons by state to create state polygons
state_geom <- unionSpatialPolygons(county_geom, county_geom$STATE)

# convert state geometry to tidy dataframe for plotting
state_coords <- fortify(state_geom) %>%
  
  # rename state code column, filter out Puerto Rico and mangled Alaskan islands
  select(state = id, everything()) %>%
  filter(state != '72', long < -60)
```

```{r education_map}
# get educational attainment data from 2018 ACS
education_county <- get_acs(variables = 'C15002B_003',
                           year = 2018,
                           geography = 'county',
                           summary_var = 'C15002B_001',
                           cache_table = T) %>%
  
  # create percentage of NOT less than high school diploma, extract state FIPS codes
  mutate(percent = (summary_est - estimate) / summary_est * 100,
         state = str_extract(GEOID, '[:digit:]{2}')) %>%
  
  # join ACS data with county coordinates for map plot
  full_join(county_coords, by = 'GEOID')

# filter out Puerto Rico and plot map, filled by percent high school grads
education_county %>%
  filter(state != '72') %>%
  ggplot() +
  geom_polygon(aes(long, lat, group = group, 
                   fill = percent),
               color = '#666666',
               size = 0.2) +
  
  # change map projection
  coord_map('conic', lat0 = 30) +
  
  # change color scales to match percentage distribution
  scale_fill_gradientn(breaks = c(0, 85, 92, 96, 100),
                       values =c(0, 85, 92, 96, 100) / 100,
                       colors = brewer.pal(4, 'RdYlGn'),
                       na.value = 'gray',
                       guide = 'legend',
                       labels = c('0-85%', '85-92%', '92-96%', '96-100%', '100%')) +
  scale_color_gradientn(breaks = c(0, 85, 92, 96, 100),
                        values = c(0, 0.85, 0.92, 0.96, 1),
                        colors = brewer.pal(4, 'RdYlGn'),
                        na.value = 'gray',
                        guide = 'legend',
                        labels = c('0-85%', '85-92%', '92-96%', '96-100%', '100%')) +
  
  # add state boundary lines
  geom_path(aes(long, lat, group = group, fill = NULL),
            color = '#666666',
            data = state_coords) +
  
  # add title and source note
  labs(title = 'Percent of Black Males With At Least High School Diploma, by County',
       subtitle = 'Nationwide, highest educational attainment for 30.8% of black men is less than a high school diploma.',
       caption = 'Source: 2018 American Community Survey. Data for some counties missing.') +
  
  # remove theme, relocate legend
  theme_void() +
  theme(legend.position = c(0.9, 0.5),
        legend.title = element_blank())

# save map to files
ggsave('images/education_map.png', width = 9, height = 5, dpi = 'retina')
```

```{r homes_data, warning = F, message = F}
# suppress warnings and messages about columns and rows that are later discarded

# skip empty rows at top of table, set column types, clean column names with janitor
homes <- read_excel('data/ann19t_22.xlsx', skip = 3, col_types = c('text', rep('numeric',27))) %>%
  janitor::clean_names() %>%
  
  # rename 1996 column to remove 'footnote'1' superscript, remove 2002 column to use revised data
  select(race = x1, x1996 = x19961, everything(), 
         -x2002, x2002 = x2002r1) %>%
  
  # extract relevant rows
  slice(4:6) %>%
  
  # pivot table to tidy format
  pivot_longer(., cols = x1996:x2019, 
               names_to = 'year', values_to = 'percent',
               names_prefix = 'x') %>%
  
  # clean labels for race
  mutate(race = str_extract(race, '([:alpha:]{5}|[:alpha:]{3}\\-[:alpha:]{8}[:blank:][:alpha:]{5})'),
         year = as.numeric(year))
```

```{r homes_plot}
# create table for annotations
rl <- tibble(x = c(2004.5, 2004), y = c(78.5,52),
             race = c('Non-Hispanic White', 'Black'))

# create table from homes data for ribbon between black and white
diff.area <- homes %>% 
  select(year, race, percent) %>%
  filter(race != 'White') %>%
  mutate(race = if_else(race == 'Black', 'Black', 'NHW')) %>%
  pivot_wider(names_from = race, values_from = percent)

# plot line graph time series of Blacks and Non-Hispanic Whites
homes %>%
  filter(race != 'White') %>%
  
  ggplot() +
  geom_line(aes(year, percent, color = race),
            size = 1.5) +
  
  geom_text(aes(x, y, label = race, color = race), 
            fontface = 2,
            data = rl) +
  geom_ribbon(aes(x = year, ymin = Black, ymax = NHW),
              fill = ribbon.fill,
              data = diff.area) +
  
  scale_color_manual(values = c('#377EB8', '#6baed6')) +
  scale_y_continuous(limits = c(30, 90),
                     breaks = seq(20,90,10),
                     labels = paste(seq(20,90,10), '%', sep = '')) +
  scale_x_continuous(limits = c(1994,2020),
                     breaks = seq(1995,2020,5),
                     labels = c('\'95', '2000', paste('\'', c('05', 10, 15, 20), sep = ''))) +
  
  labs(y = 'Percentage of Home Ownership',
       x = 'Year',
       title = 'Percentage of Home Ownership by Race, 1994-2019',
       subtitle = 'The disparity in home ownership between Blacks and Non-Hispanic Whites, about 28%,\nhas remained relatively constant over the last 25 years.',
       caption = 'Source: U.S. Census Bureau, Current Population Survey/Housing Vacancy Survey, March 10, 2020.') +
  
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_line(linetype = 2),
        legend.position = 'none')

ggsave('images/homes.png', width = 9, height = 5, dpi = 'retina')

diff.area %>% 
  mutate(diff = NHW - Black) %>% 
  summarize(mean = mean(diff), min = min(diff), max = max(diff))
```

```{r prison_data, message = F, warning = F}
# load in 2018 data, skipping non-data rows and removing empty columns
# note: data is X per 100,000 people
prison.18 <- read_csv('data/prison/p18/p18t06.csv', skip = 11) %>%
  select(-starts_with('X')) %>%
  janitor::clean_names() %>%
  slice(1:11) %>%
  
  # change year to numeric, remove old year column
  mutate(year = as.numeric(year_a)) %>%
  select(year, everything(), -year_a)


# remove extra bits from column names
colnames(prison) <- str_remove(colnames(prison), '_[:alpha:]')

prison.race <- prison %>%
  
  # select relevant columns
  select(year, white, black) %>%
  
  # convert table to tidy format (race column, rate column)
  pivot_longer(cols = c(white, black), names_to = 'race', values_to = 'rate')

prison.ribbon <- prison %>% select(year, black, white)
prison.labels <- tibble(x = c(2013.5),
                        y = c(1930,170),
                        labels = c('black', 'white'))
read_csv('data/prison/p08/p08t06.csv', skip = 10)#[c(1:9),-c(3,5,7,9,)]
```

```{r prison_plot, message = F, warning = F}
# draw plot of incarceration rates by race
prison.race %>%
  
  # add line plots, ribbon for area between lines, and text labels
  ggplot() +
  geom_line(aes(year, rate, color = race),
            size = 1.5) +
  geom_ribbon(aes(year, ymin = white, ymax = black),
              fill = ribbon.fill,
              data = prison.ribbon) +
  geom_text(aes(x, y, label = str_to_title(labels), color = labels),
            fontface = 2,
            data = prison.labels) +
  
  # add title, subtitle, axes labels, caption
  labs(title = 'U.S. Incarceration Rates by Race, 2008-2018',
       subtitle = 'While the difference in incarceration rates has narrowed in recent years, in 2018\nblack Americans were incarcerated at nearly 6 times the rate of white Americans.', 
       x = 'Year', y = 'Incarceration Rate\n(per 100,000)',
       caption = 'Source: Bureau of Justice Statistics, Federal Justice Statistics Program, U.S. Census Bureau') +
  
  # modify scales to fit data and match color schemes
  scale_x_continuous(limits = c(2008,2018),
                     breaks = c(2008:2018),
                     labels = c('\'08', '\'09', 2010, paste('\'', c(11:18), sep = ''))) +
  scale_y_continuous(limits = c(0,2250)) +
  scale_color_manual(values = c('#377EB8', '#6baed6')) +
  
  theme(panel.grid.minor.x = element_blank(),
        legend.position = 'none')

ggsave('images/prison.png', width = 9, height = 5, dpi = 'retina')

# create table showing rate of Black Incarceration as multiple of White rate
prison.ribbon %>% mutate(rate.multiple = black / white) %>% slice(1,11)
```

```{r police, include = F}
# Source: Bureau of Justice Statistics, Law Enforcement Management and Administrative Statistics survey, 2016.
# read_csv('data/local_police/lpd16pt06.csv')
```

```{r white_wealth_data}
# get acs data for black population
black_pops <- get_acs('county',
                      year = 2018,
                      variables = 'B01001B_001',
                      summary_var = 'B01001_001',
                      cache_table = T)

# find FIPS codes for top 100 counties by black pop
black_fips <- black_pops %>% 
  mutate(percent = 100 * estimate / summary_est) %>%
  arrange(desc(percent)) %>%
  # slice(1:100) %>%
  select(black.pop = estimate, percent, GEOID)

# find income data for above counties
income_acs <- get_acs('county',
                         year = 2018,
                         variables = 'B19013B_001',
                         summary_var = 'B19013A_001',
                         cache_table = T) %>%
  mutate(white.factor = summary_est / estimate) %>%
  full_join(black_fips, by = c('GEOID'))

# rename columns for clearer names, filter out counties with very small black populations
county_income <- income_acs %>%
  filter(!is.na(moe), percent >= 5) %>%
  arrange(desc(white.factor)) %>%
  select(GEOID, NAME, black.income = estimate, white.income = summary_est, white.factor:percent) %>%
  mutate(white.income = white.income / 1000,
         black.income = black.income / 1000)

# create linear model of income and percet black
income_model <- lm(white.income ~ black.income, data = county_income)
rsq <- summary(income_model)$r.squared
coefs <- income_model$coefficients

# create tibble for line labels
lines <- tibble(x = c(107,106),
                y= c(96, 133),
                labels = c('\'Ideal\' Line',
                           'Line of Best Fit'),
                bold = c(1,2))

lbf.height = 18.75

rsq_text <- tibble(x = c(106, 75),
                y= c(127, lbf.height),
                labels = c('R^2==0.522',
                           'white.income == 0.841 %*% black.income + 26539.83'),
                hjust = c(0.5,0.2),
                bold = 2)
```

```{r white_wealth_plot, fig.height=5, fig.width=9}
# create plot
county_income %>%
  ggplot() +
  
  # add points for counties
  geom_point(aes(black.income, white.income),
             alpha = 0.4,
             pch = 19,
             color = '#6baed6') +
  
  # add line of best fit and 'ideal' line
  geom_abline(slope = coefs['black.income'], 
              intercept = coefs['(Intercept)'],
              size = 1.5, color = '#377EB8') +
  geom_abline(slope = 1, intercept = 0, lty = 2) + 
  
  # add labels for lines
  geom_text(aes(x = x, y = y, 
                label = labels, 
                fontface = bold),
            data = lines)+
  
  # simplify scales for readability
  scale_x_continuous(breaks = seq(0,125,25),
                     labels = paste('$', seq(0,125,25), 'K', sep = '')) +
  scale_y_continuous(breaks = seq(0,125,25),
                     labels = paste('$', seq(0,125,25), 'K', sep = '')) +
  
  # add labels, title, etc.
  labs(title = 'Median Household Income, Black vs. White by County',
       subtitle = 'Includes counties in the 50 states, D.C., and Puerto Rico where the black population is at least 5% of the white population.',
       x = 'Median Household Income, Black',
       y = 'Median Household Income, White',
       caption = 'Source: 2018 American Community Survey') +
  
  # add legend for best fit (separate because parse = T)
  geom_text(aes(x = x, y = y, 
                label = labels,
                hjust = hjust),
            parse = T,
            fontface = 2,
            data = rsq_text) +
  
  geom_segment(aes(x = 61, xend = 64,
                   y = lbf.height, yend = lbf.height),
               size = 1.5, color = '#377EB8')

 # ggsave('images/county_income.png', width = 9, height = 5, dpi = 'retina')
```

```{r county_income_gt}
# create gt of top ten counties with highest white/black income
county_income %>% 
  
  # arrange by white income multiplier, add ranking
  arrange(desc(white.factor)) %>% 
  mutate(white.income = white.income * 1000,
         black.income = black.income * 1000,
         Rank = row_number()) %>%
  
  # select top 10 rows and rearrange/drop columns for table order
  slice(1:10) %>% 
  select(Rank, everything(), -c(GEOID, percent)) %>% 
  
  # create gt and add title, income spanner group
  gt() %>%
  tab_header(title = 'Median Household Income by Race and County',
             subtitle = 'Ten Counties with highest \'White Income Multiplier\' are shown') %>%
  tab_spanner(columns = vars(black.income,white.income),
              label = 'Median Household Income') %>%
  
  # align columns and reformat numbers, incomes
  cols_align('center', columns = vars(black.income, white.income, black.pop, white.factor)) %>%
  fmt_currency(columns = vars(black.income, white.income),
               decimals = 0) %>%
  fmt_number(columns = vars(black.pop), decimals = 0) %>%
  fmt_number(columns = vars(white.factor), decimals = 3) %>%
  
  # rename columns
  cols_label(NAME = 'County',
             black.income = 'Black',
             white.income = 'White',
             black.pop = 'Black Population',
             white.factor = 'White Income Multiplier')
  
```



